development: &defaults
  adapter: postgresql
  host: localhost
  database: epure_development
  username:
  password:
  pool: 5
  timeout: 5000

test:
  <<: *defaults
  database: epure_test

production:
  <<: *defaults
  database: epure_production
